/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());
    DefaultTableModel model;
    
    private static final String CONCLUIDA = "Concluir";
    private static final String NAO_CONCLUIDA = "Não Concluida";
    
    private final ArrayList<String> tarefas = new ArrayList<>();
    private final ArrayList<String> tarefasFiltradas = new ArrayList<>();
    private int indiceTarefaSelecionada;
    
    public NewJFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) jTableTarefas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDescricaoTarefa = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jComboBoxFiltroStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jButtonConcluirTarefas = new javax.swing.JButton();
        jButtonRemoverTarefa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldDescricaoTarefa.addActionListener(this::jTextFieldDescricaoTarefaActionPerformed);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(this::jButtonAdicionarActionPerformed);

        jComboBoxFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Concluídos", "Não concluído" }));
        jComboBoxFiltroStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxFiltroStatusFocusGained(evt);
            }
        });
        jComboBoxFiltroStatus.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jComboBoxFiltroStatusComponentMoved(evt);
            }
        });
        jComboBoxFiltroStatus.addActionListener(this::jComboBoxFiltroStatusActionPerformed);

        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefa", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTarefas);

        jButtonConcluirTarefas.setText("Concluir");
        jButtonConcluirTarefas.addActionListener(this::jButtonConcluirTarefasActionPerformed);

        jButtonRemoverTarefa.setText("Remover");
        jButtonRemoverTarefa.addActionListener(this::jButtonRemoverTarefaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonConcluirTarefas)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRemoverTarefa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcluirTarefas)
                    .addComponent(jButtonRemoverTarefa)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescricaoTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoTarefaActionPerformed

    private void jComboBoxFiltroStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroStatusActionPerformed

    private void jComboBoxFiltroStatusComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxFiltroStatusComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroStatusComponentMoved

    private void jComboBoxFiltroStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxFiltroStatusFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroStatusFocusGained

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
 if (jTextFieldDescricaoTarefa.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(null,"A descrição da de tarefa não pode ser vazia!");
          return;
      }
      if (hasTarefaRepetida(jTextFieldDescricaoTarefa.getText())){
          JOptionPane.showMessageDialog(null,"A tarefa " + jTextFieldDescricaoTarefa.getText() + "já existe!");
          return;  
      }
      
      tarefas.add(jTextFieldDescricaoTarefa.getText() + ";" + NAO_CONCLUIDA);
      
      preencherTabela();
      
      jTextFieldDescricaoTarefa.setText("");
    }                                                      

    public boolean hasTarefaRepetida(String novaTarefa){
        
        
        for (String tarefa : tarefas){
            String dados [] = tarefa.split(";");
            
            if (novaTarefa.toLowerCase().equals(dados[0].toLowerCase())) {
                return true;
            }
            
        }
        
        return false;
    }
    
    private void preencherTabela(){
        ArrayList<String> listaTarefas;
        
        if (jComboBoxFiltroStatus.getSelectedIndex() > 0) {
            listaTarefas = tarefasFiltradas;
        }else {
            listaTarefas = tarefas;
            
            model.setRowCount(0);
            for (String tarefa : listaTarefas){
                String[] dados = tarefa.split(";");
                
                model.addRow(new Object[]{
                dados[0],
                dados[1]        
            });
            }
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonRemoverTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverTarefaActionPerformed
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
        if (linhaSelecionada< 0){
            JOptionPane.showMessageDialog(null, "nenhuma tarefa foi selecionada!");
            return;
        }
        
        int opcao = JOptionPane.showConfirmDialog(null, "deseja realmente excluir a tarefa");
        
        String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
        
        int indiceTarefaSelecionada = tarefas.indexOf(tarefaSelecionada);
        
        if(opcao == JOptionPane.YES_OPTION){
            tarefas.remove(indiceTarefaSelecionada);
            preencherTabela();
        }
        
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jButtonRemoverTarefaActionPerformed

    private void jButtonConcluirTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirTarefasActionPerformed
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
        if (linhaSelecionada < 0){
            JOptionPane.showMessageDialog(null, "nenhuma tarefa foi selecionada!");
            return;
        }
        
        String tarefaSelecionada = recuperarTarefa (linhaSelecionada);
        
        int inidiceTarefa = tarefas.indexOf(tarefaSelecionada);
        
        String[] dados = tarefas.get(indiceTarefaSelecionada).split(";");
        
        tarefas.set(indiceTarefaSelecionada, dados[0] + ";" + CONCLUIDA);
        
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jButtonConcluirTarefasActionPerformed

    private void filtrarTabela(){
        int opcao = jComboBoxFiltroStatus.getSelectedIndex();
        tarefasFiltradas.clear();
        
        String[] dados;
        
        for(String tarefa : tarefas){
            dados = tarefa.split(";");
            
            switch (opcao) {
                case 0:
                    tarefasFiltradas.add(tarefa);
                    break;
                case 1:
                    if (dados[1]. equals(CONCLUIDA)) {
                        tarefasFiltradas.add(tarefa);
                        
                    }
                    
                    break;
                case 2:
                   if (dados[1].equals(NAO_CONCLUIDA)){
                       tarefasFiltradas.add(tarefa);
                   } 
                default:
                    throw new AssertionError();
            }
        }
    }
    
    private String recuperarTarefa(int indiceTarefa) {
        if (jComboBoxFiltroStatus.getSelectedIndex()> 0){
            return tarefasFiltradas.get(indiceTarefa);       
        }else{
            return tarefas.get(indiceTarefa);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonConcluirTarefas;
    private javax.swing.JButton jButtonRemoverTarefa;
    private javax.swing.JComboBox<String> jComboBoxFiltroStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextField jTextFieldDescricaoTarefa;
    // End of variables declaration//GEN-END:variables
}
